version: "3"
services:
  apache:
    build: apache
    restart: always
    volumes:
      - ./apache/content:/var/www/html/
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8090:80"
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/content:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_volume:/var/lib/sql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
volumes:
  db_volume:
