version: "3"

services:
  web:
    build: docker/php
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./app:/var/www/html/
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8889:3306"
    volumes:
      - db_volume:/var/lib/sql
      - ./docker/mariadb:/docker-entrypoint-initdb.d
volumes:
  db_volume: